// <auto-generated />
using System;
using Manhwa.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Manhwa.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301141629_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Manhwa.Domain.Entities.Bookmark", b =>
                {
                    b.Property<int>("BookmarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bookmark_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookmarkId"));

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("BookmarkId")
                        .HasName("pk_bookmarks");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_bookmarks_user_id");

                    b.ToTable("bookmarks", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Chapter", b =>
                {
                    b.Property<int>("ChapterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chapter_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChapterId"));

                    b.Property<float>("ChapterNumber")
                        .HasColumnType("real")
                        .HasColumnName("chapter_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("ChapterId")
                        .HasName("pk_chapters");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_chapters_language_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_chapters_story_id");

                    b.ToTable("chapters", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.ChapterImage", b =>
                {
                    b.Property<int>("ChapterImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("chapter_image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChapterImageId"));

                    b.Property<int>("ChapterId")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.HasKey("ChapterImageId")
                        .HasName("pk_chapter_images");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_chapter_images_chapter_id");

                    b.ToTable("chapter_images", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GenreId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.HasKey("GenreId")
                        .HasName("pk_genres");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_genres_slug");

                    b.ToTable("genres", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("LanguageId")
                        .HasName("pk_languages");

                    b.ToTable("languages", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationId"));

                    b.Property<int?>("ChapterId")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int?>("VolumeId")
                        .HasColumnType("integer")
                        .HasColumnName("volume_id");

                    b.HasKey("NotificationId")
                        .HasName("pk_notifications");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_notifications_chapter_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_notifications_story_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_notifications_volume_id");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.ReadingHistory", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.Property<int?>("ChapterId")
                        .HasColumnType("integer")
                        .HasColumnName("chapter_id");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("VolumeId")
                        .HasColumnType("integer")
                        .HasColumnName("volume_id");

                    b.HasKey("UserId", "StoryId")
                        .HasName("pk_reading_histories");

                    b.HasIndex("ChapterId")
                        .HasDatabaseName("ix_reading_histories_chapter_id");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_reading_histories_language_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_reading_histories_story_id");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_reading_histories_volume_id");

                    b.ToTable("reading_histories", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Story", b =>
                {
                    b.Property<int>("StoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StoryId"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("OtherTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("other_title");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer")
                        .HasColumnName("release_year");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("StoryId")
                        .HasName("pk_stories");

                    b.HasIndex("TypeId")
                        .HasDatabaseName("ix_stories_type_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stories_user_id");

                    b.ToTable("stories", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.StoryBookmark", b =>
                {
                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("BookmarkId")
                        .HasColumnType("integer")
                        .HasColumnName("bookmark_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("StoryId", "UserId", "BookmarkId")
                        .HasName("pk_story_bookmarks");

                    b.HasIndex("BookmarkId")
                        .HasDatabaseName("ix_story_bookmarks_bookmark_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_story_bookmarks_user_id");

                    b.ToTable("story_bookmarks", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.StoryGenre", b =>
                {
                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer")
                        .HasColumnName("genre_id");

                    b.HasKey("StoryId", "GenreId")
                        .HasName("pk_story_genres");

                    b.HasIndex("GenreId")
                        .HasDatabaseName("ix_story_genres_genre_id");

                    b.ToTable("story_genres", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.StoryRating", b =>
                {
                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Score")
                        .HasColumnType("numeric")
                        .HasColumnName("score");

                    b.HasKey("StoryId", "UserId")
                        .HasName("pk_story_ratings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_story_ratings_user_id");

                    b.ToTable("story_ratings", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Type", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("type_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("TypeId")
                        .HasName("pk_story_types");

                    b.ToTable("story_types", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<short>("Role")
                        .HasColumnType("smallint")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Volume", b =>
                {
                    b.Property<int>("VolumeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("volume_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VolumeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("LanguageId")
                        .HasColumnType("integer")
                        .HasColumnName("language_id");

                    b.Property<int>("StoryId")
                        .HasColumnType("integer")
                        .HasColumnName("story_id");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbnail_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<float>("VolumeNumber")
                        .HasColumnType("real")
                        .HasColumnName("volume_number");

                    b.HasKey("VolumeId")
                        .HasName("pk_volumes");

                    b.HasIndex("LanguageId")
                        .HasDatabaseName("ix_volumes_language_id");

                    b.HasIndex("StoryId")
                        .HasDatabaseName("ix_volumes_story_id");

                    b.ToTable("volumes", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.VolumeImage", b =>
                {
                    b.Property<int>("VolumeImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("volume_image_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VolumeImageId"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer")
                        .HasColumnName("order_index");

                    b.Property<int>("VolumeId")
                        .HasColumnType("integer")
                        .HasColumnName("volume_id");

                    b.HasKey("VolumeImageId")
                        .HasName("pk_volume_images");

                    b.HasIndex("VolumeId")
                        .HasDatabaseName("ix_volume_images_volume_id");

                    b.ToTable("volume_images", (string)null);
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Bookmark", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.User", "User")
                        .WithMany("Bookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookmarks_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Chapter", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Language", "Language")
                        .WithMany("Chapters")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapters_languages_language_id");

                    b.HasOne("Manhwa.Domain.Entities.Story", "Story")
                        .WithMany("Chapters")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapters_stories_story_id");

                    b.Navigation("Language");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.ChapterImage", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Images")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chapter_images_chapters_chapter_id");

                    b.Navigation("Chapter");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Notification", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Chapter", "Chapter")
                        .WithMany("Notifications")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_chapters_chapter_id");

                    b.HasOne("Manhwa.Domain.Entities.Story", "Story")
                        .WithMany("Notifications")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_stories_story_id");

                    b.HasOne("Manhwa.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.HasOne("Manhwa.Domain.Entities.Volume", "Volume")
                        .WithMany("Notifications")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notifications_volumes_volume_id");

                    b.Navigation("Chapter");

                    b.Navigation("Story");

                    b.Navigation("User");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.ReadingHistory", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Chapter", "Chapter")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_reading_histories_chapters_chapter_id");

                    b.HasOne("Manhwa.Domain.Entities.Language", "Language")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_histories_languages_language_id");

                    b.HasOne("Manhwa.Domain.Entities.Story", "Story")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_histories_stories_story_id");

                    b.HasOne("Manhwa.Domain.Entities.User", "User")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reading_histories_users_user_id");

                    b.HasOne("Manhwa.Domain.Entities.Volume", "Volume")
                        .WithMany("ReadingHistories")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_reading_histories_volumes_volume_id");

                    b.Navigation("Chapter");

                    b.Navigation("Language");

                    b.Navigation("Story");

                    b.Navigation("User");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Story", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Type", "Type")
                        .WithMany("Stories")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_stories_types_type_id");

                    b.HasOne("Manhwa.Domain.Entities.User", "User")
                        .WithMany("Stories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stories_users_user_id");

                    b.Navigation("Type");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.StoryBookmark", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Bookmark", "Bookmark")
                        .WithMany("StoryBookmarks")
                        .HasForeignKey("BookmarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_bookmarks_bookmarks_bookmark_id");

                    b.HasOne("Manhwa.Domain.Entities.Story", "Story")
                        .WithMany("StoryBookmarks")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_bookmarks_stories_story_id");

                    b.HasOne("Manhwa.Domain.Entities.User", "User")
                        .WithMany("StoryBookmarks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_bookmarks_users_user_id");

                    b.Navigation("Bookmark");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.StoryGenre", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Genre", "Genre")
                        .WithMany("StoryGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_genres_genres_genre_id");

                    b.HasOne("Manhwa.Domain.Entities.Story", "Story")
                        .WithMany("StoryGenres")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_genres_stories_story_id");

                    b.Navigation("Genre");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.StoryRating", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Story", "Story")
                        .WithMany("Ratings")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_ratings_stories_story_id");

                    b.HasOne("Manhwa.Domain.Entities.User", "User")
                        .WithMany("StoryRatings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_story_ratings_users_user_id");

                    b.Navigation("Story");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Volume", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Language", "Language")
                        .WithMany("Volumes")
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_volumes_languages_language_id");

                    b.HasOne("Manhwa.Domain.Entities.Story", "Story")
                        .WithMany("Volumes")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_volumes_stories_story_id");

                    b.Navigation("Language");

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.VolumeImage", b =>
                {
                    b.HasOne("Manhwa.Domain.Entities.Volume", "Volume")
                        .WithMany("Images")
                        .HasForeignKey("VolumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_volume_images_volumes_volume_id");

                    b.Navigation("Volume");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Bookmark", b =>
                {
                    b.Navigation("StoryBookmarks");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Chapter", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Notifications");

                    b.Navigation("ReadingHistories");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Genre", b =>
                {
                    b.Navigation("StoryGenres");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Language", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("ReadingHistories");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Story", b =>
                {
                    b.Navigation("Chapters");

                    b.Navigation("Notifications");

                    b.Navigation("Ratings");

                    b.Navigation("ReadingHistories");

                    b.Navigation("StoryBookmarks");

                    b.Navigation("StoryGenres");

                    b.Navigation("Volumes");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Type", b =>
                {
                    b.Navigation("Stories");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookmarks");

                    b.Navigation("Notifications");

                    b.Navigation("ReadingHistories");

                    b.Navigation("Stories");

                    b.Navigation("StoryBookmarks");

                    b.Navigation("StoryRatings");
                });

            modelBuilder.Entity("Manhwa.Domain.Entities.Volume", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Notifications");

                    b.Navigation("ReadingHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
